### ISSUE TITLE
libbde does not work with Windows 10 out of the box

### ISSUE THREAD

**Issue by bethlogic** [libyal/libbde#10]
I haven't done a lot of digging into the actual issue, but Bit Locker for Windows 10 is different and adjustments will need to be made to libbde.  I have a rest image you can use, and will look into it soon-ish(?).  What this issue lacks in detail to fix it, it makes up for in providing amble notice of a new "feature".

$ bdeinfo -r <recovery-key> -o $((512*1411072)) desk-base.dd
bdeinfo 20160418

Unable to open: desk-base.dd.
libbde_metadata_entry_read: unsupported FVE metadata entry version.
libbde_volume_master_key_read: unable to read property metadata entry.
libbde_metadata_read_entries: unable to read volume master key.
libbde_metadata_read_block: unable to read metadata header.
libbde_volume_open_read: unable to read primary metadata block.
libbde_volume_open_file_io_handle: unable to read from file IO handle.
info_handle_open_input: unable to open input volume.

**Comment by joachimmetz** [comment]
Likely related to: https://github.com/libyal/libbde/issues/6 I'll sync with you about the test image separately.

**Comment by bethlogic** [comment]
Yes, this issue is almost certainly #6 and I just didn't actually read it because I didn't the the title was related.  Should we close this one since the other has more/better info?

**Comment by joachimmetz** [comment]
Marked as duplicate, pending release should fix #6
