### ISSUE TITLE
Extending the existing known-plaintext-attack on version and data_size fields

### ISSUE THREAD

**Issue by kholia** [libyal/libbde#13]
Hi,

I am writing a John the Ripper jumbo plugin to brute-force password protected BitLocker volumes. My project is heavily based on your libbde project.

My brute-force method uses a known plaintext attack on the decrypted contents of `metadata->password_volume_master_key->aes_ccm_encrypted_key->data`. Specifically, the `version` has to be 1 and `data_size` has to be 0x2c. This stuff is in the `libbde_metadata_read_volume_master_key` function.

Do you know about more fields within the `unencrypted_data` buffer with known values which could be used in improving the reliability of the attack ? Currently `version` and `data_size` provide 4 bytes of verification data. Having more known fields with known values would be helpful in reducing false positives encountered during the brute-forcing process.

I noticed many NULL bytes in the `unencrypted_data` buffer but I don't know what they are, and if I can use them safely in conducting the known plaintext attack.

I noticed your comment "TODO improve this check" near the `version` and `data_size` checks in `libbde/libbde_metadata.c` :-)
 
https://github.com/kholia/JohnTheRipper/blob/BitLocker/src/bitlocker_fmt_plug.c#L184 shows the known plaintext attack in action.

Thanks for your help.

**Comment by joachimmetz** [comment]
I'll get back to you as soon as time permits, libbde focus has not been built with bruteforcing BitLocker in mind

**Comment by joachimmetz** [comment]
question outside the of scope of the project, closing
