### ISSUE TITLE
Ask for help

### ISSUE THREAD

**Issue by YoyoFelix** [libyal/libbde#19]
It is really a big problem for a freshman to read such a large number of codes. So would you please add some descriptions about the lib. Plz Plz Plz. Cause it's so hard to do a integration testing without knowing what does the functions means. An excessive request from a code noob. Thanks a lot.

**Comment by joachimmetz** [comment]
@YoyoFelix can you elaborate what specific details / questions you find yourself running into?

For integration the thing that is most relevant is the main include (man 3 libbde.h)

**Comment by YoyoFelix** [comment]
@joachimmetz Sorry pal, I try to read the codes by myself for sevral days, and it's still hard for me to understand what parameter does these functions need or work out. For example, I only got the offset of the metadata, how can I run the function "libbde_volume_open_read_keys_from_metadata". Or in other ways to talk, which functions I need to add to decrypt the volume on the basis of project “bde_test_volume”. It's so sorry for trouble you. T T

**Comment by joachimmetz** [comment]
@YoyoFelix `libbde_volume_open_read_keys_from_metadata` is an internal function. 

> I need to add to decrypt the volume on the basis of project “bde_test_volume”

Roughly you'll need to call the following API functions:
```
/* To initialize and open */
libbde_volume_initialize()
libbde_volume_set_utf8_password() /* or equivalent for the credential you'll need to unlock the volume */
libbde_volume_open() /* Assumes the volume starts at offset 0 */
/* To read and seek */
libbde_volume_read_buffer()
libbde_volume_seek_offset()
/* To close and initialize */
libbde_volume_close()
libbde_volume_free()

```

**Comment by YoyoFelix** [comment]
@joachimmetz I much appreciate your helping, and all your reply helps me a lot.
