### ISSUE TITLE
Something about the calculating time

### ISSUE THREAD

**Issue by YoyoFelix** [libyal/libbde#21]
This library cost about 2 minutes to calculate the encrypted_context at the function libbde_metadata_read_volume_master_key. So is there any solutions to optimize?

**Comment by joachimmetz** [comment]
are you running into this issue by any chance?
https://github.com/libyal/libcaes/issues/1

could you try adding WINVER=0x501

**Comment by YoyoFelix** [comment]
By setting WINVER to 0x0501, the program will not run into that issue. Thanks a lot! And what's more, why using Wincrypt provides such a horribly running time.

**Comment by joachimmetz** [comment]
> And what's more, why using Wincrypt provides such a horribly running time.

This is something I need to look into when time permits. Current hypothesis this has to do how the wincrypt API is used by libcaes.

**Comment by YoyoFelix** [comment]
Thanks my codeing master. Hope that we can find the reason.

**Comment by joachimmetz** [comment]
Removing WinCrypt support, seeing it is deprecated
https://github.com/libyal/libcaes/issues/10
