### ISSUE TITLE
BDE spec: Didn't mention "COV 0001. ER", etc.

### ISSUE THREAD

**Issue by Explorer09** [libyal/libbde#26]
Hello. My I suggest one improvement of the [BDE spec](https://github.com/libyal/libbde/blob/master/documentation/BitLocker%20Drive%20Encryption%20(BDE)%20format.asciidoc)?
I have recently been experimenting with BitLocker encryption of FAT32 volumes, and I found my "discovery volume" contains "COV 0001. ER" and such for encrypted data.

For example, from an `ls -l` output when mounted in Linux:
```
...
-r--r--r-- 1 root root      32768 Mar 30  2018 COV\ 0000.\ BL*
-r--r--r-- 1 root root 4294934528 Mar 30  2018 COV\ 0000.\ ER*
-r--r--r-- 1 root root 4294934528 Mar 30  2018 COV\ 0001.\ ER*
-r--r--r-- 1 root root 4294934528 Mar 30  2018 COV\ 0002.\ ER*
-r--r--r-- 1 root root 3146153984 Mar 30  2018 COV\ 0003.\ ER*
...
```
It looks like each `. ER` file has a maximum size of 4294934528 bytes (4 GiB - 32768 bytes).
The existence of multiple `. ER` files and their size limit it not mentioned in the specification.

By the way, I encrypted this drive in Windows 10 version 1703. It's a 16 GB USB flash drive with a single FAT32 volume; partition table is MBR.

**Comment by Explorer09** [comment]
One more technical info:

From `DIR /A /X` command in Windows XP of the same volume
```
...
09/29/2017  07:42 AM          6,656 ZH-TW_~1.MUI zh-TW_BitLockerToGo.exe.mui
03/30/2018  03:51 AM         32,768 COV000~1.BL  COV 0000. BL
03/30/2018  03:51 AM      4,194,304              PAD 0000. PD
03/30/2018  03:51 AM  4,294,934,528              COV 0000. ER
03/30/2018  03:51 AM  4,294,934,528              COV 0001. ER
03/30/2018  03:51 AM  4,294,934,528              COV 0002. ER
03/30/2018  03:51 AM  3,146,153,984              COV 0003. ER
03/30/2018  03:51 AM              0              PAD 0000. NG
03/30/2018  03:51 AM              0              PAD 0001. NG
...
```

The total number of files in the volume seem to be exactly 906. The `PAD <num>. NG` files seems to be used in filling the file name entries, so that it get 906 files in the count. But I have no idea why it has to be this number.

**Comment by joachimmetz** [comment]
@Explorer09 thanks for sharing your findings I've update the documentation in https://github.com/libyal/libbde/commit/a5a78a51c9a5756365d1878a8173340c578655c2
