### ISSUE TITLE
A Question

### ISSUE THREAD

**Issue by sspring** [libyal/libbde#32]
It's just a question.https://github.com/libyal/libbde/blob/aa1aba109f82a14bc141f1b069ae51e93e20dfe6/include/libbde/features.h.in#L35 
Do you suggest that all functions with LIBBDE_HAVE_BFIO defined shouldn't be used on Windows?    
so I can't use `libbde_check_volume_signature_file_io_handle`  on windows if I don't define HAVE_LIBBFIO directly.

**Comment by joachimmetz** [comment]
> Do you suggest that all functions with LIBBDE_HAVE_BFIO defined shouldn't be used on Windows?

No, this line suggest that to use libbfio on Windows (Visual Studio primarily) you'll have to define HAVE_LIBBFIO

**Comment by sspring** [comment]
Got it.Thanks a lot.
