### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by tlhszc** [libyal/libbde#42]
I have downloaded “libbde-alpha-20190317.tar.gz” software,  and installed it through setup.py in the Kali Linux system environment. How can I use this software under Kali linux? Do you have software instructions?

**Comment by joachimmetz** [comment]
What software are you hoping to use under Kali? This project mainly provides a library that you program against. There are couple of tools for convenience. Please read https://github.com/libyal/libbde/wiki/Building#read-first on how to build those.

Setup.py will only build the Python bindings. On how to use them see: https://github.com/libyal/libbde/wiki/Development

**Comment by tlhszc** [comment]
I want to use libbde to decrypt BitLocker hard disk partitions with fvek keys.

**Comment by tlhszc** [comment]
> 你希望在Kali下使用什么软件？该项目主要提供您编程的库。为方便起见，有几种工具。请阅读https://github.com/libyal/libbde/wiki/Building#read-first了解如何构建它们。
> 
> Setup.py只会构建Python绑定。关于如何使用它们，请参阅：[https](https://github.com/libyal/libbde/wiki/Development)：[//github.com/libyal/libbde/wiki/Development](https://github.com/libyal/libbde/wiki/Development)

I want to use libbde to decrypt BitLocker hard disk partitions with fvek keys

**Comment by joachimmetz** [comment]
If Kali does not provide the bdeinfo and bdemount binaries already build them using https://github.com/libyal/libbde/wiki/Building. Instructions on how to use bdemount https://github.com/libyal/libbde/wiki/Mounting. See `bdemount -h` how to specify the FVEK and or TWEAK keys

**Comment by tlhszc** [comment]
> 如果Kali没有提供bdeinfo和bdemount二进制文件已经使用https://github.com/libyal/libbde/wiki/Building构建它们。有关如何使用bdemount [https://github.com/libyal/libbde/wiki/Mounting的说明](https://github.com/libyal/libbde/wiki/Mounting)。了解`bdemount -h`如何指定FVEK和/或TWEAK键

This software is already available in kali. Know the FVEK and TWEAK keys, can you mount the encrypted USB flash drive with the command "bdemount -k 3c78a84cf22b306354cd65f215d1c931:5c6c114c10a7e5b2de078c23d4295fef /dev/sdb /mnt/bde"?

**Comment by joachimmetz** [comment]
Yes if these are the correct keys you should be able mount a BDE volume in that way. If you're using /dev/sdb you might need to specify an offset as well or use /dev/sdb1 instead

**Comment by tlhszc** [comment]
> Yes if these are the correct keys you should be able mount a BDE volume in that way. If you're using /dev/sdb you might need to specify an offset as well or use /dev/sdb1 instead
<pre><font color="#EF2929"><b>root@kali</b></font>:<font color="#729FCF"><b>~</b></font># bdemount -k 3c78a84cf22b306354cd65f215d1c931:5c6c114c10a7e5b2de078c23d4295fef /dev/sdb /mnt/
bdemount 20190317

No sub system to mount BDE format.
</pre>

**Comment by tlhszc** [comment]
> Yes if these are the correct keys you should be able mount a BDE volume in that way. If you're using /dev/sdb you might need to specify an offset as well or use /dev/sdb1 instead

After running the command "bdemount-k 3c78a84cf22b306354cd65f215d1c931:5c6c114c10a7e5b2de078c23d4295fef/dev/sdb/mnt/bde", display the following information:

<pre><font color="#EF2929"><b>root@kali</b></font>:<font color="#729FCF"><b>~</b></font># bdemount -k 3c78a84cf22b306354cd65f215d1c931:5c6c114c10a7e5b2de078c23d4295fef /dev/sdb /mnt/
bdemount 20190317

No sub system to mount BDE format.
</pre>

**Comment by joachimmetz** [comment]
that is explained her https://github.com/libyal/libbde/wiki/Mounting#mounting

**Comment by tlhszc** [comment]
> that is explained here https://github.com/libyal/libbde/wiki/Mounting#mounting

Thank you for your help. I have been able to mount the U disk under kali.The reason for the above problem is that the original kalii system did not install libfuse-dev.

**Comment by joachimmetz** [comment]
Good to hear you got it working, closing this issue.
