### ISSUE TITLE
How do I use bdeinfo on a Windows volume?

### ISSUE THREAD

**Issue by xufuda** [libyal/libbde#45]
Device G has been encrypted with BitLocker，so i use dos commands 
“bdeinfo -p binarydataleo.(bitlocker password) G:” in windows 10 system,but report an error: "Unable to open: G:.
libcfile_file_open_with_error_code: unable to open file: G: with error: BitLocker".
Is there any help documentation with bdeinfo and bdemount?
Thanks!!!

**Comment by joachimmetz** [comment]
there are man pages, and wiki https://github.com/libyal/libbde/wiki/Mounting

but on Windows "G:" is a drive letter and **NOT** a device file path try `\\.\G:` instead

See https://github.com/log2timeline/dfvfs/wiki/Windows-Path-Resolver for some information on paths on Windows

**Comment by xufuda** [comment]
ok，thanks，i will try again.
