### ISSUE TITLE
Feature Request: When mounting a volume using the passphrase show the FVEK

### ISSUE THREAD

**Issue by Mips128** [libyal/libbde#51]
Dear all, 

when mounting a bitlocker encrypted partition using bdemount and the correct passphrase, we would like to dump/extract/see the FVEK. The reasoning for this is that we want to have the correct FVEK as a reference when doing testing on RAM dumps. 

Is there an easy way to do this using bdemount/bdeinfo? 

Thank you in advance for any help.

Best Regards
Dennis

**Comment by joachimmetz** [comment]
> Is there an easy way to do this using bdemount/bdeinfo?

I'm hesitant to add this to the info or mount tool, since you have a very exotic use case. The information you are looking for should be in the debug output.

**Comment by joachimmetz** [comment]
no additional response, assuming question has been answered
