### ISSUE TITLE
Read errors if trying to read decrypted virtual data past 1TB

### ISSUE THREAD

**Issue by gregfreemyer** [libyal/libbde#58]
libbde version 20220121

For perhaps the first time I have a bunch of 2TB external USB drives I'm trying to image. after decrypting.

I used bdemount to create a virtual fille (/mnt/bde1).  It works great for the first 1,000 GB, but then it fails.

In troubleshooting I tried a simple "od -c -j $((1024 * 1024 * 1024 * 1000)) /mnt/bde1 | less" and it works as expected.  

That is a 1000 GB offset -- no problem.

But   "od -c -j $((1024 * 1024 * 1024 * 1024) /mnt/bde1"  fails.

This is a 1024 GB offset and it fails with an i/o error

**Comment by joachimmetz** [comment]
Can you check if int is 32-bit for your compilation? Also see: https://github.com/libyal/libbde/issues/47

**Comment by joachimmetz** [comment]
Made some changes in https://github.com/libyal/libbde/commit/bc60762ca72e5366f9ca4d13903399f13f82b107 in case the 64-bit int does not work.
