### ISSUE TITLE
New XTS-AES mode

### ISSUE THREAD

**Issue by anocs** [libyal/libbde#6]
Any plans to support  XTS-AES mode introduced in Windows 10 Threshold 2 (1511 build 10586)

**Comment by joachimmetz** [comment]
When I have the time or an immediate need for the functionality.
However if you have a test image or can make one that you can share that might speed up getting this functionality in.

**Comment by anocs** [comment]
I'll prepare some test dd images.

**Comment by joachimmetz** [comment]
Thx, that would be useful.

**Comment by anocs** [comment]
Please find link to OneDrive with sample Bitlocker "dd" images:
http://1drv.ms/1l0wKZe

There are 3 images:
1. Unencrypted reference image 
2. Bitlocker AES-CBC mode ("classic" BDE)
3. Bitlocker AES-XTS mode ("new" Windows 10 TH2 BDE)

Text password for BDE is: Apple123!

**Comment by joachimmetz** [comment]
Thanks I'll have a look as soon as time permits

**Comment by joachimmetz** [comment]
FYI I've started looking into this, but available time is limited at the moment.

**Comment by anocs** [comment]
Perfect news, no need to hurry, take your time, enjoy X-mas.

**Comment by anocs** [comment]
One notice - those "dd" images are full disk/device images, not just partition - for test I had to use offset of 65536 bytes (128 sectors of 512 bytes)

**Comment by joachimmetz** [comment]
Thanks, I'd noticed ;)

**Comment by joachimmetz** [comment]
@anocs to confirm is the sample AES-XTS with a 128-bit key? or 256-bit key?

Would you be able to provide me with a small sample of the other as well to make sure the library works on that variation as well. Thanks in advance.

**Comment by anocs** [comment]
Sorry for delay. 
Please find XTS AES 128/256 sample "dd" images in file "Bitlocker_examples_XTS_AES_128_256.7z " on http://1drv.ms/1l0wKZe

- Text password for BDE is: Apple123!
- Recovery keys are in appropriate text files next to "dd" images.
- "dd" images are full disk/device images, not just partition.

**Comment by joachimmetz** [comment]
Thanks, I'll continue looking at the format. Might take a bit seeing available time.

**Comment by joachimmetz** [comment]
Finally got around to it, try pending release 20170901.
