### ISSUE TITLE
Ask about using libbde to decrypt the bitlocker usb drive

### ISSUE THREAD

**Issue by tridungxo** [libyal/libbde#63]
Hi, currently I'm trying to find a solution for my task. I'm working on QT project using mingw or msvc 64 bit compiler on windows 10 platform. The QT app should be able to check the USB drive connected is encrypted or not (usb using bitlocker encrypted) and able to decrypt usb drive to read data from usb. I feel that libbde can do it but not sure
I would like to confirm that, if yes, is there any example or API description docs I can follow, thanks

**Comment by joachimmetz** [comment]
>  is there any example or API description docs

https://github.com/libyal/libbde/wiki/C-development

> I feel that libbde can do it but not sure I would like to confirm that

libbde can read bitlocker encrypted volumes, reading from an USB device likely needs some tweaking given required device access and volume layout of the USB device
