### ISSUE TITLE
Gather information about mounted devices

### ISSUE THREAD

**Issue by Taloncor** [libyal/libbde#7]
I am currently working with devices that have been encrypted with BitlockerToGo and I was wondering if it is possible certain information after (bde)mounting the device:
- Is there any way to check if a device has already been mounted via bdemount?
- Is it possible to determine the device a bdemount originated from? 

Thanks for your time.

**Comment by joachimmetz** [comment]
Can you explain me the context in which you are asking these questions? System administration or forensic activity reconstruction. For the former it depends on you the mount sub-system you are using, e.g. fuse or dokan. Can you let me know what sub-system you are using?

**Comment by Taloncor** [comment]
It is more or less system administration and I'm using fuse.

**Comment by Taloncor** [comment]
First off: I am using Fuse and it is more about system administration.

Context: I want to use the bitlocker devices in certain workflows (copying files mostly) that require the device to be already decrypted/mounted. Therefore I would like to check if a given devices has already been bdemounted.

**Comment by joachimmetz** [comment]
From the top of my mind there are various option here:

1. maybe use dfvfs instead
2. use a specific convention that easily allows you to determine this
3. depends on your fuse configuration, last time I checked fuse tries to hide as much of the original mount point for privacy reasons; not sure maybe fuse has tools to view more info about the mount under the user that mounted it

**Comment by Taloncor** [comment]
Thanks for the reply.  I'll just stick with option 2 and adjusted the workflow accordingly.

I am hesitant to open another question but I ran into further trouble with a NTFS-BitlockerToGo device. Is there any way to access the unencrypted part of such a device? With vfat/exfat I am able to just mount the device but it seems that the ntfs-device does not contain any recognizable filesystem. Any ideas? 

To clarify:
- Created ntfs filesystem on usb stick
- encrypted device with bitlocker on windows
- Would like to mount device and read unencrypted content

**Comment by joachimmetz** [comment]
> I am hesitant to open another question but I ran into further trouble with a NTFS-BitlockerToGo device.

@Taloncor I must have missed this update.

> Is there any way to access the unencrypted part of such a device?

Yes, no need for libbde there, just mount the file system as-is.

> With vfat/exfat I am able to just mount the device but it seems that the ntfs-device does not contain any recognizable filesystem.

Are you sure it has an unencrypted file system?
