### ISSUE TITLE
What is the status of this library?

### ISSUE THREAD

**Issue by eabase** [libyal/libbde#71]
What is the status of this library? 
Does it work with Windows-11? 
With `XTS-AES256` and `encrypt-on-write` devices?
What is the latest version?

**Comment by joachimmetz** [comment]
The answers to most of your questions that can be found in the README and on the release page. For `encrypt-on-write` see https://github.com/libyal/libbde/issues/39

**Comment by eabase** [comment]
@joachimmetz

Your README doesn't mention any of the 2 terms above!
And where's your "RELEASE" page?

**Comment by joachimmetz** [comment]
> Your README doesn't mention any of the 2 terms above!

Which "terms" ? If you are not specific I cannot help you

> What is the status of this library?

From the readme:

```
Project information:

* Status: alpha
```

Does it work with Windows-11?

* what do you mean? "work with"

> With XTS-AES256 and encrypt-on-write devices?

From the readme:

```
Supported encryption methods:

* AES-CBC
* AES-XTS

Unsupported BDE formats:

* Bitlocker Used Disk Space Only encryption
```

What is the latest version?

* https://github.com/libyal/libbde/releases

> And where's your "RELEASE" page?

See previous link
