### ISSUE TITLE
What to "provide" for error no upstream tarball found at ../libbde_20240625.orig.tar

### ISSUE THREAD

**Issue by eabase** [libyal/libbde#72]
The latest tar file you have in releases is labelled `20240502`, so I compiled from git clone, and I still get asked for something different:

`no upstream tarball found at ../libbde_20240625.orig.tar.{bz2,gz,lzma,xz}`

How to fix?

**Comment by joachimmetz** [comment]
I assume you used dpkg-buildpackage, you'll have to make sure to correctly name the upstream tarball. This is not a libbde issue, please read the man page of dpkg-buildpackage. Marking a invalid given this is not a libbde related issue.
