### ISSUE TITLE
Cannot unlock an E01 using recovery password

### ISSUE THREAD

**Issue by darshjain** [libyal/libbde#73]
![image](https://github.com/user-attachments/assets/a716be29-9769-4bd1-9fd4-a469ed3fc84d)

Attached is the screenshot of an E01 which i wish to unlock and use but it throws the given error when trying to use with recovery password, can you please further help me out on that, below are some details that i extracted from other tools that could be of help
```
Created By AccessData® FTK® Imager 4.7.1.2 

Case Information: 
Acquired using: ADI4.7.1.2
Case Number: 001
Evidence Number: 001
Unique Description: 
Examiner: Brijesh
Notes:  

--------------------------------------------------------------

Information for F:\Bitlocker Pendrive E01 File\Bitlocker Pendrive:

Physical Evidentiary Item (Source) Information:
[Device Info]
 Source Type: Physical
[Drive Geometry]
 Cylinders: 1,912
 Tracks per Cylinder: 255
 Sectors per Track: 63
 Bytes per Sector: 512
 Sector Count: 30,720,000
[Physical Drive Information]
 Drive Model: VendorCo ProductCode USB Device
 Drive Serial Number: 3247771287026363354
 Drive Interface Type: USB
 Removable drive: True
 Source data size: 15000 MB
 Sector count:    30720000
[Computed Hashes]
 MD5 checksum:    c06bdf0b071b91aeab5a47719d1e30b7
 SHA1 checksum:   9503ac14fc5a101d5bd3a938774b2344ba5b63d4

Image Information:
 Acquisition started:   Fri Sep 13 13:45:53 2024
 Acquisition finished:  Fri Sep 13 14:00:36 2024
 Segment list:
  F:\Bitlocker Pendrive E01 File\Bitlocker Pendrive.E01

Image Verification Results:
 Verification started:  Fri Sep 13 14:00:36 2024
 Verification finished: Fri Sep 13 14:01:18 2024
 MD5 checksum:    c06bdf0b071b91aeab5a47719d1e30b7 : verified
 SHA1 checksum:   9503ac14fc5a101d5bd3a938774b2344ba5b63d4 : verified
 COMPUTED HASH :  c06bdf0b071b91aeab5a47719d1e30b7
 COMPUTED HASH :  9503ac14fc5a101d5bd3a938774b2344ba5b63d4

Image Verification Results:
 Verification started:  Fri Dec 13 12:06:27 2024
 Verification finished: Fri Dec 13 12:07:03 2024
 MD5 checksum:    c06bdf0b071b91aeab5a47719d1e30b7 : verified
 SHA1 checksum:   9503ac14fc5a101d5bd3a938774b2344ba5b63d4 : verified
```

**Comment by bgrundy** [comment]
Have you tried using `ewfmount` (from `libewf`) first?  Then use `bdeinfo` or `bdemount` on the appropriate volume in resulting raw image.  I don't believe the `libbde` tools are meant to run directly on EWF containers.

**Comment by darshjain** [comment]
Yes, I tried that, I dont think its working rightly, I have created a relevant issue on that repository as well -
https://github.com/libyal/libewf/issues/209

**Comment by joachimmetz** [comment]
Per @bgrundy the libbde tools only support raw storage media format and make sure to point it at the offset of the start oft eh bitlocker volume. Closing this issue given this is not the intended way to use the tools.

**Comment by darshjain** [comment]
But I believe that E01 is supported by libewf and hence should work with libbde right?

**Comment by joachimmetz** [comment]
> But I believe that E01 is supported by libewf and hence should work with libbde right?

No, this is not how it works. If you want something that combines the functionality of both have a look at https://github.com/log2timeline/dfvfs
