### ISSUE TITLE
What is Key Protector Type 0x500?

### ISSUE THREAD

**Issue by hillu** [libyal/libbde#8]
I recently came across an image for which `bdeinfo` did not recognize the key protector type, 0x500.

Could this mean that `LIBBDE_KEY_PROTECTION_TYPE_TPM` (0x100) is combined with 0x400 for something else, maybe a start-up PIN?

**Comment by joachimmetz** [comment]
> Could this mean that LIBBDE_KEY_PROTECTION_TYPE_TPM (0x100) is combined with 0x400 for something else, maybe a start-up PIN?

Maybe without a controlled test hard to say. 

Also thanks for the PR I'll merge the changes separately.

**Comment by joachimmetz** [comment]
Added some notes to the documentation for now https://github.com/libyal/libbde/commit/c2e89c646fb8fcff5c1545d89f17accc175574ab
